name = "simple-post"
license = "MIT"
source_repo = ""
description = "simple-post theme based on Twitter BootStrap"
tags = ["post", "category"]
categories = ["featured"]

[author]
    name = "koduki"
    email = "pascalm3+github@gmail.com"
